version: 2
jobs:
  build:
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: "Build Docker image and push to Docker Hub (if on master)"
        command: |
          TAG_BASE="${CIRCLE_PROJECT_USERNAME?}/comicslate"
          TAG="${TAG_BASE?}:${CIRCLE_BUILD_NUM?}"
          docker build -t "${TAG?}" .
          docker tag "${TAG?}" "${TAG_BASE?}:latest"
          if [ "${CIRCLE_BRANCH}" = master ]; then
            echo "${DOCKER_PASSWORD?}" | docker login -u "${DOCKER_USER?}" --password-stdin
            docker push "${TAG?}"
            docker push "${TAG_BASE?}:latest"
          fi
