#!/usr/bin/env bash

set -e

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

update_whitelisted_ips() {
	curl -sSL https://www.cloudflare.com/ips-v{4,6} | \
		sed 's/^/  Require ip /' \
		> /etc/apache2/conf-available/cloudflare_ip.part
	getent ahosts pool.sysmon.hetzner.com | \
		awk '!seen[$1]++ { print "  Require ip", $1 }' | \
		sort > /etc/apache2/conf-available/hetzner_ip.part
}

create_archives() {
	local archives_root=/var/www/.htsecure/archives
	mkdir -p "${archives_root?}"
	local archives_prefix="$(date '+%Y-%m-%d_%H-%M-%S')"

	7zr a "${archives_root?}/pages_${archives_prefix?}.7z" \
		/var/www/comicslate.org/data/pages >/dev/null
	7zr a "${archives_root?}/meta_${archives_prefix?}.7z" \
		/var/www/comicslate.org/data/meta >/dev/null
}

upload_backup() {
	gcloud auth activate-service-account \
		--key-file=/var/www/.htsecure/backup-service-account.json
	local backup_round="$(($(date +%_j) % 10))"
	tar -cp --exclude-tag-all=purgefile --exclude=u \
		/var/www/comicslate.org | \
		gsutil cp - \
		"gs://comicslate-org-backup/backup-${backup_round?}.tar"
}

cron() {
	update_whitelisted_ips
	# Reload Apache and FTP daemons to pick up new certificates.
	service apache2 reload
	# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911396
	service vsftpd restart || true

	create_archives || failure=1
	upload_backup || failure=1
	service vmtouch restart || failure=1
	test -z "$failure"
}

start() {
	update_whitelisted_ips

	# See Dockerfile for rationale why it's not a symlink.
	rm -rf /etc/nullmailer
	cp -r /var/www/.htsecure/nullmailer /etc &&
		chown -R mail:mail /etc/nullmailer &&
		chmod -R u=rX,g=rX,o= /etc/nullmailer

	service cron start
	service nullmailer start
	service syslog-ng start
	# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911396
	service vsftpd start || true
	service vmtouch start

	# When we're in a TTY, assume that this is a debug session.
	if [ -t 1 ]; then
		apachectl start || apachectl -D NoSSL
		exec bash
	fi

	exec apache2-foreground
}

"${1?command argument required}"
