name: ci

on:
  push:
    branches:
      - master
      - stable

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # Custom path context so that ".git" subdirectory is around.
          context: .
          push: true
          tags: "dotdoom/comicslate:${{ github.ref == 'refs/heads/stable' && 'stable' || 'latest' }}"
